import HeroVideo from '@/components/hero-video';
import Link from 'next/link';
import {ArrowDown,ArrowUpRight} from 'lucide-react';
import {site} from '@/content/site';
import Reveal from '@/components/reveal';
import EditorialImage from '@/components/editorial-image';
import {Label,MoreLink} from '@/components/shared';
export default function Home(){const h=site.home;return <main id="main" className="mr-home">
<section className={`mr-hero ${h.hero.video?"has-video":""}`} aria-labelledby="hero-brand">{h.hero.video&&<HeroVideo src={h.hero.video} poster={h.hero.poster} pauseLabel={h.hero.pauseLabel} playLabel={h.hero.playLabel}/> }<p className="mr-hero-role">{site.englishName}</p><h1 id="hero-brand" className="mr-hero-brand">{site.brand}</h1><EditorialImage className="mr-hero-person" src={h.hero.portrait} alt={h.hero.portraitAlt} note={h.hero.portraitNote} portrait priority/><div className="mr-hero-aside"><span>{h.hero.disciplines}</span><span>{site.title}<br/>{site.subtitle}<br/>Based in {site.location}</span></div><div className="mr-hero-bottom"><a href="#philosophy"><ArrowDown size={14}/>{h.hero.scroll}</a><span>{h.hero.index}</span></div></section>
<section id="philosophy" className="mr-section mr-philosophy"><Label number="02">{h.philosophy.label}</Label><Reveal className="mr-philosophy-copy"><h2>{h.philosophy.title}</h2><div><p>{h.philosophy.text}</p><span className="practice-english">{h.philosophy.english}</span></div></Reveal></section>
<section className="mr-section mr-works"><div className="section-heading"><Label number="03">{h.works.label}</Label><MoreLink href="/works">{h.works.link}</MoreLink></div><Reveal><h2 className="mr-section-title">{h.works.title}</h2><p className="placeholder">{h.works.note}</p></Reveal><div className="mr-work-list">{site.works.map((w,i)=><Reveal key={w.slug}><Link className={`mr-work mr-work-${i+1}`} href={`/works/${w.slug}`}><EditorialImage src={w.image} alt={`${w.name}展示图片占位，非项目现场`} note={w.imageNote}/><div className="mr-work-caption"><span className="mr-work-number">0{i+1}</span><div><h3>{w.name}</h3><p>{w.english}</p></div><span className="mr-work-status">{w.status}<span className="view-project">View Project ↗</span></span><span className="mr-work-arrow"><ArrowUpRight size={27}/></span></div></Link></Reveal>)}</div></section>
<section className="mr-section mr-about"><Label number="04">{h.about.label}</Label><div className="mr-about-grid"><Reveal><EditorialImage className="mr-documentary" src={h.about.image} alt={h.about.imageAlt} note={h.about.imageNote}/></Reveal><Reveal className="mr-about-copy"><h2>{h.about.title}</h2><p>{site.bio}</p><p className="placeholder">{site.bioNote}</p><MoreLink href="/about">{h.about.link}</MoreLink></Reveal></div></section>
<section className="mr-section mr-journal"><div className="section-heading"><Label number="05">{h.journal.label}</Label><MoreLink href="/journal">{h.journal.link}</MoreLink></div><Reveal><h2 className="mr-section-title">{h.journal.title}</h2><p className="mr-journal-intro">{h.journal.intro}</p></Reveal><div className="mr-journal-grid">{site.journal.map((j,i)=><Reveal key={j.id}><Link className="mr-journal-card" href={`/journal#${j.id}`}><EditorialImage src={j.image} alt={`${j.label}栏目配图占位`} note={j.image?'氛围占位 · 非本人原创影像':'栏目影像待提供'}/><div className="mr-journal-caption"><span>0{i+1} / {j.label}</span><h3>{j.title}<ArrowUpRight size={18}/></h3></div></Link></Reveal>)}</div></section>
<section className="mr-section mr-contact"><Label number="06">{h.contact.label}</Label><Reveal><h2>{h.contact.title}</h2><div className="mr-contact-grid"><p>{h.contact.intro}</p><div><span>{h.contact.emailLabel}</span>{site.email?<a href={`mailto:${site.email}`}>{site.email}<ArrowUpRight size={18}/></a>:<p>{h.contact.emailPlaceholder}</p>}</div><div><span>{h.contact.wechatLabel}</span><p>{site.wechat||h.contact.wechatPlaceholder}</p></div></div></Reveal></section>
</main>}
